---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - autossh
  - awscli
  - bat
  - ctop
  - fd
  - fzf
  - gh
  - git
  - grex
  - hadolint
  - htop
  - mtr
  - neovim
  - nmap
  - prettyping
  - ripgrep
  - rustscan
  - ssh-copy-id
  - tealdeer
  - tmux
  - wget
  - youtube-dl
  - zoxide
  - zsh

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alacritty
  - alfred
  - boostnote
  - dash
  - docker
  - dropbox
  - firefox
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - iina
  - keka
  - setapp
  - slack
  - surge
  - telegram
  - vscodium
  - welly

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 539883307, name: "LINE" }
  - { id: 961632517, name: "Be Focused Pro - Focus Timer & Goal Tracker" }
  - { id: 1037779758, name: "Best Trace" }

mas_email: ""
mas_password: ""
