---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - asdf
  - bat
  - croc
  - ctop
  - exa
  - fd
  - fzf
  - gh
  - git
  - gping
  - grex
  - hadolint
  - htop
  - mtr
  - neovim
  - nmap
  - ripgrep
  - rustscan
  - ssh-copy-id
  - tealdeer
  - tmux
  - wget
  - youtube-dl
  - zoxide
  - zsh

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alacritty
  - alfred
  - bartender
  - dash
  - docker
  - firefox
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - fsnotes
  - google-chrome
  - iina
  - keka
  - secretive
  - setapp
  - slack
  - surge
  - telegram

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 539883307, name: "LINE" }

mas_email: ""
mas_password: ""
